### ISSUE TITLE
Why are there only 1999 training images and 100 testing images? 

### ISSUE THREAD

**Issue by yiminglin-ai** [JPlin/Relabeled-HELEN-Dataset#1]
Hi,
Thank you for your work. I have downloaded your data and I am wondering why there are only 1999 training images and 100 testing images? According to your paper, there should be 2000 training, 230 validation and 100 testing images. 
Many thanks.

**Comment by yiminglin-ai** [comment]
@JPlin

**Comment by JPlin** [comment]
1. We train our model only on 1999 training images(HELEN*), and the missing one maybe because of some mistakes when collecting relabeled data.
2. Due to limited human resources, we did not relabel the validation set,
